/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jolasa;

import model.Hitza;

/**
 *
 * @author otero.haritz
 */
public class UrkatuaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UrkatuaJFrame
     */
    public UrkatuaJFrame() {
        initComponents();
         this. setTitle("Haritz Otero Urkatua");
        jLabelIrudia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irudiak/" + hutsak + ".jpg")));
        jLabelAsmatutakoak.setText(hitza.getStrAsmatutakoa());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldHizkia = new javax.swing.JTextField();
        jButtonEgiaztatu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelIrudia = new javax.swing.JLabel();
        jLabelAsmatutakoak = new javax.swing.JLabel();
        jLabelEzDauzkanak = new javax.swing.JLabel();
        jLabelIrabazi = new javax.swing.JLabel();
        jButtonBerria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("URKATUAREN JOLASA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Aukeratu hizkia:");

        jTextFieldHizkia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonEgiaztatu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEgiaztatu.setText("EGIAZTATU!!");
        jButtonEgiaztatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEgiaztatuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Hitz ezkutuak ez dituen hizkiak:");

        jLabelAsmatutakoak.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelAsmatutakoak.setToolTipText("");

        jLabelEzDauzkanak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelIrabazi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonBerria.setText("PARTIDA BERRIA");
        jButtonBerria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBerriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldHizkia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEgiaztatu))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelEzDauzkanak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAsmatutakoak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelIrabazi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabelIrudia, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBerria, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonBerria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHizkia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEgiaztatu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelEzDauzkanak, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabelAsmatutakoak, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIrabazi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelIrudia, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEgiaztatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEgiaztatuActionPerformed
        
        if (!jLabelEzDauzkanak.getText().contains(jTextFieldHizkia.getText().toUpperCase())) {
            boolean aurkitua = hitza.egiaztatu(jTextFieldHizkia.getText().toUpperCase().charAt(0));
            if (!aurkitua) {
                hutsak ++; 
                jLabelEzDauzkanak.setText(jLabelEzDauzkanak.getText()+jTextFieldHizkia.getText().toUpperCase()+", ");
                jLabelIrudia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irudiak/" + hutsak + ".jpg")));
            
            }
            
            if(aurkitua) {
                jLabelAsmatutakoak.setText(hitza.getStrAsmatutakoa());
            }
           
        }
        if(hitza.getStrAsmatutakoa().equals(hitza.getHitza())){
            jLabelIrabazi.setText("IRABAZI DUZU!!");
            
            
        }
        
        if(hutsak == 7){
            jLabelIrabazi.setText("GALDU DUZU!!");
            
        }
         


        
    }//GEN-LAST:event_jButtonEgiaztatuActionPerformed

    private void jButtonBerriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBerriaActionPerformed
        
        hutsak =0;
        Hitza hitza = new Hitza();
        jLabelAsmatutakoak.setText(hitza.getStrAsmatutakoa());
        jLabelIrudia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irudiak/" + hutsak + ".jpg")));
        jLabelEzDauzkanak.setText("");
        
    }//GEN-LAST:event_jButtonBerriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrkatuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrkatuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrkatuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrkatuaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrkatuaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBerria;
    private javax.swing.JButton jButtonEgiaztatu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAsmatutakoak;
    private javax.swing.JLabel jLabelEzDauzkanak;
    private javax.swing.JLabel jLabelIrabazi;
    private javax.swing.JLabel jLabelIrudia;
    private javax.swing.JTextField jTextFieldHizkia;
    // End of variables declaration//GEN-END:variables

private Hitza hitza = new Hitza();
private int hutsak = 0;
}
