/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1;

/**
 *
 * @author otero.haritz
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogHiztegiaBistaratu = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHiztegia = new javax.swing.JTextArea();
        jButtonGorde = new javax.swing.JButton();
        jButtonTxertatu = new javax.swing.JButton();
        jButtonIrten = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelEuskaraz = new javax.swing.JLabel();
        jLabelGazteleraz = new javax.swing.JLabel();
        jTextFieldEuskaraz = new javax.swing.JTextField();
        jTextFieldGazteleraz = new javax.swing.JTextField();
        jButtonHiztegiOsoa = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("HIZTEGI OSOA");

        jTextAreaHiztegia.setColumns(20);
        jTextAreaHiztegia.setRows(5);
        jScrollPane1.setViewportView(jTextAreaHiztegia);

        jButtonGorde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGorde.setText("GORDE ETA ITXI");
        jButtonGorde.setActionCommand("GORDE");
        jButtonGorde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGordeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogHiztegiaBistaratuLayout = new javax.swing.GroupLayout(jDialogHiztegiaBistaratu.getContentPane());
        jDialogHiztegiaBistaratu.getContentPane().setLayout(jDialogHiztegiaBistaratuLayout);
        jDialogHiztegiaBistaratuLayout.setHorizontalGroup(
            jDialogHiztegiaBistaratuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogHiztegiaBistaratuLayout.createSequentialGroup()
                .addGroup(jDialogHiztegiaBistaratuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogHiztegiaBistaratuLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogHiztegiaBistaratuLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jDialogHiztegiaBistaratuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGorde))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jDialogHiztegiaBistaratuLayout.setVerticalGroup(
            jDialogHiztegiaBistaratuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogHiztegiaBistaratuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButtonGorde, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonTxertatu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTxertatu.setText("TXERTATU");
        jButtonTxertatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTxertatuActionPerformed(evt);
            }
        });

        jButtonIrten.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonIrten.setText("IRTEN");
        jButtonIrten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrtenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("HITZ BERRIA");

        jLabelEuskaraz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEuskaraz.setText("Euskaraz:");

        jLabelGazteleraz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelGazteleraz.setText("Gazteleraz:");

        jTextFieldEuskaraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEuskarazActionPerformed(evt);
            }
        });

        jButtonHiztegiOsoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonHiztegiOsoa.setText("HIZTEGI OSOA");
        jButtonHiztegiOsoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHiztegiOsoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGazteleraz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldGazteleraz))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEuskaraz)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEuskaraz, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIrten, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonHiztegiOsoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTxertatu)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEuskaraz)
                    .addComponent(jTextFieldEuskaraz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGazteleraz)
                    .addComponent(jTextFieldGazteleraz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTxertatu)
                    .addComponent(jButtonHiztegiOsoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIrten)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEuskarazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEuskarazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEuskarazActionPerformed

    private void jButtonTxertatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTxertatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTxertatuActionPerformed

    private void jButtonHiztegiOsoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHiztegiOsoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHiztegiOsoaActionPerformed

    private void jButtonIrtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrtenActionPerformed
        
    }//GEN-LAST:event_jButtonIrtenActionPerformed

    private void jButtonGordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGordeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGordeActionPerformed

    public static View viewaSortuBistaratu() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
            }
        });
        return v;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonGorde;
    javax.swing.JButton jButtonHiztegiOsoa;
    javax.swing.JButton jButtonIrten;
    javax.swing.JButton jButtonTxertatu;
    javax.swing.JDialog jDialogHiztegiaBistaratu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEuskaraz;
    private javax.swing.JLabel jLabelGazteleraz;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextArea jTextAreaHiztegia;
    javax.swing.JTextField jTextFieldEuskaraz;
    javax.swing.JTextField jTextFieldGazteleraz;
    // End of variables declaration//GEN-END:variables
}
